In [1]:
import numpy as np
import numpy.random as rand

# Gaussian Elimination

In [18]:
def gauss(B):
    A = B.copy()
    if not A.shape[0] + 1 == A.shape[1]:
        return 'Wrong matrix shape'
    for i in range(0, A.shape[0]):
        maxEl = np.absolute(A)[i:,i].argmax() + i
        A[[i, maxEl]] = A[[maxEl, i]]
        if abs(A[i, i]) < 1e-6:
            return 'Matrix rank less than n'
        for j in range(i + 1, A.shape[0]):
            coef = -A[j, i] / A[i, i]
            for k in range(i, A.shape[1]):
                A[j, k] = A[j, k] + coef*A[i, k]
    for i in range(A.shape[0] - 1, -1, -1):
        for j in range(i - 1, -1, -1):
            coef = -A[j, i] / A[i, i]
            A[j, i] = 0
            A[j, -1] = A[j, -1] + coef * A[i, -1]
        A[i, -1] = A[i, -1] / A[i, i]
        A[i, i] = 1
    return A[:, -1]

In [21]:
with open('inputGaussianElimination.txt') as f:
    lines = f.readlines()
#for i in range(len(lines)):
    #A = np.matrix(lines[i], dtype = 'float')
    #print(str(i + 1) + ':')
    A = rand.rand(4, 5)
    print(A)
    x = gauss(A)
    #print(A[:, :-1])
    print(np.matmul(A[:, :-1], x))
    

[[ 0.16565275  0.18964667  0.87414801  0.07464922  0.14539189]
 [ 0.52858743  0.3596162   0.14884961  0.74031922  0.21595881]
 [ 0.12265811  0.40224702  0.41956961  0.22433909  0.951902  ]
 [ 0.56205059  0.28183385  0.47559347  0.24545669  0.016428  ]]
[ 0.14539189  0.21595881  0.951902    0.016428  ]


# Jacobi Method

In [9]:
def jacobi(A, x, eps):
    R = A.copy()[:,:-1]
    g = A.copy()[:, -1]
    Drev = np.zeros(R.shape, dtype = 'float')
    for i in range(R.shape[0]):
        R[i, i] = 0
        if(A[i, i] != 0):
            Drev[i, i] = 1 / A[i, i]
    R = np.matmul(Drev, -R)
    g = np.matmul(Drev, g)
    while True:
        pr = x.copy()
        x = np.matmul(R, x) + g
        if np.linalg.norm(x - pr) < eps:
            break
    return x

In [ ]:
def hilb(int n)

In [10]:
with open('inputIterativeMethods.txt') as f:
    lines = f.readlines()
for i in range(len(lines)):
    A = np.matrix(lines[i], dtype = 'float')
    print(str(i + 1) + ':')
    print(jacobi(A, np.ones([1,A.shape[0]], dtype = 'float').transpose(), 1e-6))

1:
[[ 7.1111107 ]
 [-3.22222137]]
2:
[[ 0.99999995]
 [ 2.00000008]
 [-1.00000006]
 [ 1.00000009]]
3:
[[ 1.]
 [ 1.]]
4:
[[ 1.]
 [ 1.]]


# Gauss–Seidel method

In [11]:
def gaussSeidel(A, x, eps):
    pr = x.copy()
    while True:
        for i in range(x.shape[0]):
            x[i] = A[i, -1]
            for j in range(i):
                x[i] = x[i] - A[i, j] * x[j]
            for j in range(i + 1, x.shape[0]):
                x[i] = x[i] - A[i, j] * pr[j]
            x[i] = x[i] / A[i, i]
        if np.linalg.norm(x - pr) < eps:
            break
        [x, pr] = [pr, x]
    return x

In [12]:
with open('inputIterativeMethods.txt') as f:
    lines = f.readlines()
for i in range(len(lines)):
    A = np.matrix(lines[i], dtype = 'float')
    print(str(i + 1) + ':')
    print(gaussSeidel(A, np.ones([1,A.shape[0]], dtype = 'float').transpose(), 1e-6))

1:
[[ 7.1111107 ]
 [-3.22222193]]
2:
[[ 1.00000004]
 [ 2.        ]
 [-1.00000001]
 [ 1.        ]]
3:
[[ 1.]
 [ 1.]]
4:
[[ 1.]
 [ 1.]]
